Feature/inscripcion curso
Brau1973/gest-edu-back pull request #50
Opened 2024-05-31 23:03 UTC by Gon2812

Inscripción a Curso de Asignatura

2024-06-01 22:37 UTC, silBH commented on src/main/java/com/tecnoinf/gestedu/services/implementations/InscripcionCursoServiceImpl.java
> +                    if (auxInscripcionCurso.getCalificacion().equals(CalificacionCurso.EXONERADO)) {
También habría que chequear si el curso lo aprobó por examen. con un if igual . CalificacioExamen.APROBADO.
Hice una funcion hace un rato, en curso y en examen repository para obtener los aprobados para un estudiante.

2024-06-02 00:37 UTC, Brau1973 requested changes

2024-06-02 00:37 UTC, Brau1973 commented on src/main/java/com/tecnoinf/gestedu/models/InscripcionCurso.java
Falta el estado, ver modelo de domino

2024-06-02 00:37 UTC, Brau1973 commented on src/main/java/com/tecnoinf/gestedu/controllers/InscripcionCursoController.java
> +    public ResponseEntity<InscripcionCursoDTO> registerCurso(@RequestBody InscripcionCursoDTO inscripcionCursoDTO) throws ParseException {
Ponele otro nombre, algo tipo createInscripcionCurso, nuevaInscripcionCurso...

2024-06-03 02:18 UTC, closed without merging